# Generated by Django 4.2.5 on 2023-10-20 15:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0002_alter_userprofile_address_alter_userprofile_birthday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='account',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fb_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='group',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='login_times',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='must_change_password',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='privacy_policy',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(default='normal', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='unread_records',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verified',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weight',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
