# Generated by Django 4.2.5 on 2023-10-23 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0005_alter_userprofile_birthday_alter_userprofile_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(default='未設置', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='fcm_id',
            field=models.CharField(default='未設置', max_length=100),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='after_recording',
            field=models.CharField(max_length=100),
        ),
    ]
