# Generated by Django 4.2.5 on 2023-10-23 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0006_alter_userprofile_address_alter_userprofile_fcm_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersetting',
            name='after_recording',
            field=models.IntegerField(default=0),
        ),
    ]
