# Generated by Django 4.2.5 on 2023-10-23 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0007_alter_usersetting_after_recording'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersetting',
            name='after_meal',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='no_recording_for_a_day',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='over_max_or_under_min',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='unit_of_height',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='unit_of_sugar',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='unit_of_weight',
            field=models.IntegerField(default=1),
        ),
    ]
