# Generated by Django 4.2.5 on 2023-10-23 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0010_alter_userprofile_address_alter_userprofile_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
