# Generated by Django 4.2.5 on 2023-10-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0011_alter_userprofile_gender_alter_userprofile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermedical',
            name='anti_hypertensives',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usermedical',
            name='diabetes_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usermedical',
            name='insulin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usermedical',
            name='oad',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='after_meal',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='after_recording',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='no_recording_for_a_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='over_max_or_under_min',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='unit_of_height',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='unit_of_sugar',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='unit_of_weight',
            field=models.BooleanField(default=True),
        ),
    ]
