# Generated by Django 4.2.5 on 2023-10-23 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0012_alter_usermedical_anti_hypertensives_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usera1c',
            name='a1c',
            field=models.IntegerField(default=0),
        ),
    ]
