# Generated by Django 4.2.5 on 2023-10-23 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0013_alter_usera1c_a1c'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercare',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
