# Generated by Django 4.2.5 on 2023-10-24 02:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0014_alter_usercare_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usera1c',
            name='a1c',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usercare',
            name='member_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usercare',
            name='message',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usercare',
            name='reply_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userdiet',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userdiet',
            name='tag',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
