# Generated by Django 4.2.5 on 2023-10-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0021_alter_usercare_reply_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercare',
            name='member_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='usercare',
            name='reply_id',
            field=models.IntegerField(default=1),
        ),
    ]
