# Generated by Django 4.2.5 on 2023-10-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0022_alter_usercare_member_id_alter_usercare_reply_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(default='0910888888', max_length=50),
        ),
    ]
