# Generated by Django 4.2.5 on 2023-10-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0023_alter_userprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersetting',
            name='over_max_or_under_min',
            field=models.BooleanField(default=False),
        ),
    ]
