# Generated by Django 4.2.5 on 2023-11-15 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('body_fat', models.FloatField()),
                ('bmi', models.FloatField()),
                ('recorded_at', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '體重',
                'verbose_name_plural': '體重',
                'db_table': 'Body_Weight',
            },
        ),
        migrations.CreateModel(
            name='vip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('remark', models.FloatField(max_length=100)),
                ('started_at', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('after_recording', models.BooleanField(default=False)),
                ('no_recording_for_a_day', models.BooleanField(default=False)),
                ('over_max_or_under_min', models.BooleanField(default=True)),
                ('after_meal', models.BooleanField(default=True)),
                ('unit_of_sugar', models.BooleanField(default=True)),
                ('unit_of_weight', models.BooleanField(default=True)),
                ('unit_of_height', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '使用者設定',
                'verbose_name_plural': '使用者設定',
                'db_table': 'Body_User_Setting',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birthday', models.CharField(max_length=50)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('gender', models.BooleanField()),
                ('fcm_id', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '使用者資料',
                'verbose_name_plural': '使用者資料',
                'db_table': 'Body_User_Profile',
            },
        ),
        migrations.CreateModel(
            name='UserDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sugar_delta_max', models.FloatField(default=10.0)),
                ('sugar_delta_min', models.FloatField(default=1.0)),
                ('sugar_morning_max', models.FloatField(default=10.0)),
                ('sugar_morning_min', models.FloatField(default=1.0)),
                ('sugar_evening_max', models.FloatField(default=10.0)),
                ('sugar_evening_min', models.FloatField(default=1.0)),
                ('sugar_before_max', models.FloatField(default=10.0)),
                ('sugar_before_min', models.FloatField(default=1.0)),
                ('sugar_after_max', models.FloatField(default=10.0)),
                ('sugar_after_min', models.FloatField(default=1.0)),
                ('systolic_max', models.IntegerField(default=10)),
                ('systolic_min', models.IntegerField(default=1)),
                ('diastolic_max', models.IntegerField(default=10)),
                ('diastolic_min', models.IntegerField(default=1)),
                ('pulse_max', models.IntegerField(default=10)),
                ('pulse_min', models.IntegerField(default=1)),
                ('weight_max', models.FloatField(default=10.0)),
                ('weight_min', models.FloatField(default=1.0)),
                ('bmi_max', models.FloatField(default=10.0)),
                ('bmi_min', models.FloatField(default=1.0)),
                ('body_fat_max', models.FloatField(default=10.0)),
                ('body_fat_min', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '使用者預設值',
                'verbose_name_plural': '使用者預設值',
                'db_table': 'Body_User_Default',
            },
        ),
        migrations.CreateModel(
            name='unread_records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unread_1', models.IntegerField()),
                ('unread_2', models.IntegerField()),
                ('unread_3', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diabets_type', models.IntegerField()),
                ('oad', models.IntegerField()),
                ('insulin', models.IntegerField()),
                ('antu_hypertensive', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '病史',
                'verbose_name_plural': '病史',
                'db_table': 'Body_Medical',
            },
        ),
        migrations.CreateModel(
            name='Drug_Used',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('recorded_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '藥物使用紀錄',
                'verbose_name_plural': '藥物使用紀錄',
                'db_table': 'Body_Drug_Used',
            },
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('meal', models.IntegerField()),
                ('tag', models.CharField(max_length=100)),
                ('image', models.IntegerField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('recorded_at', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '飲食日記',
                'verbose_name_plural': '飲食日記',
                'db_table': 'Body_Diet',
            },
        ),
        migrations.CreateModel(
            name='Care',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.IntegerField()),
                ('reply_id', models.IntegerField()),
                ('message', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '照護者',
                'verbose_name_plural': '照護者',
                'db_table': 'Body_Care',
            },
        ),
        migrations.CreateModel(
            name='BloodSuger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sugar', models.FloatField()),
                ('timeperiod', models.IntegerField()),
                ('recorded_at', models.CharField(max_length=50)),
                ('drug', models.IntegerField()),
                ('execrise', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '血糖',
                'verbose_name_plural': '血糖',
                'db_table': 'Body_Blood_Suger',
            },
        ),
        migrations.CreateModel(
            name='BloodPressure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systolic', models.IntegerField()),
                ('diastolic', models.IntegerField()),
                ('pulse', models.IntegerField()),
                ('recorded_at', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '血壓',
                'verbose_name_plural': '血壓',
                'db_table': 'Body_Blood_Pressure',
            },
        ),
        migrations.CreateModel(
            name='A1c',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a1c', models.CharField(max_length=50)),
                ('recorded_at', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'A1c',
                'verbose_name_plural': 'A1c',
                'db_table': 'Body_A1c',
            },
        ),
    ]
