# Generated by Django 4.2.6 on 2023-12-07 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0)),
                ('body_fat', models.FloatField(default=0)),
                ('bmi', models.FloatField(default=0)),
                ('recorded_at', models.DateTimeField(default='2023-12-07 21:38:33')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'User_Weight',
            },
        ),
        migrations.CreateModel(
            name='User_VIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0)),
                ('remark', models.FloatField(default=0)),
                ('started_at', models.DateTimeField(default='2023-12-07 21:38:33')),
                ('ended_at', models.DateTimeField(default='2023-12-07 21:38:33')),
                ('created_at', models.DateTimeField(default='2023-12-07 21:38:33')),
                ('updated_at', models.DateTimeField(default='2023-12-07 21:38:33')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'User_VIP',
            },
        ),
        migrations.CreateModel(
            name='User_Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('after_recording', models.BooleanField(default=False)),
                ('no_recording_for_a_day', models.BooleanField(default=False)),
                ('over_max_or_under_min', models.BooleanField(default=True)),
                ('after_meal', models.BooleanField(default=True)),
                ('unit_of_sugar', models.BooleanField(default=True)),
                ('unit_of_weight', models.BooleanField(default=True)),
                ('unit_of_height', models.BooleanField(default=True)),
                ('created_at', models.CharField(default='2023-12-07 21:38:33:38:33', max_length=50)),
                ('updated_at', models.CharField(default='2023-12-07 21:38:33:38:33', max_length=50)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'User_Setting',
            },
        ),
        migrations.CreateModel(
            name='User_Medical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diabetes_type', models.IntegerField(default=0, null=True)),
                ('oad', models.IntegerField(default=0, null=True)),
                ('insulin', models.IntegerField(default=0, null=True)),
                ('anti_hypertensives', models.IntegerField(default=0, null=True)),
                ('created_at', models.DateTimeField(default='2023-12-07 21:38:33')),
                ('updated_at', models.DateTimeField(default='2023-12-07 21:38:33')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'User_Medical',
            },
        ),
        migrations.CreateModel(
            name='User_Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.IntegerField(default=0)),
                ('name', models.CharField(default='', max_length=50, null=True)),
                ('recorded_at', models.DateTimeField(default='2023-12-07 21:38:33')),
                ('created_at', models.DateTimeField(default='2023-12-07 21:38:33')),
                ('updated_at', models.DateTimeField(default='2023-12-07 21:38:33')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'User_Drug',
            },
        ),
        migrations.CreateModel(
            name='User_Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=255, null=True)),
                ('meal', models.IntegerField(default=0, null=True)),
                ('tag', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('image', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('lat', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('lng', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('recorded_at', models.DateTimeField(default='2023-12-07 21:38:33')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'User_Diary',
            },
        ),
        migrations.CreateModel(
            name='User_Default',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sugar_delta_max', models.FloatField(default=10.0)),
                ('sugar_delta_min', models.FloatField(default=1.0)),
                ('sugar_morning_max', models.FloatField(default=10.0)),
                ('sugar_morning_min', models.FloatField(default=1.0)),
                ('sugar_evening_max', models.FloatField(default=10.0)),
                ('sugar_evening_min', models.FloatField(default=1.0)),
                ('sugar_before_max', models.FloatField(default=10.0)),
                ('sugar_before_min', models.FloatField(default=1.0)),
                ('sugar_after_max', models.FloatField(default=10.0)),
                ('sugar_after_min', models.FloatField(default=1.0)),
                ('systolic_max', models.IntegerField(default=10)),
                ('systolic_min', models.IntegerField(default=1)),
                ('diastolic_max', models.IntegerField(default=10)),
                ('diastolic_min', models.IntegerField(default=1)),
                ('pulse_max', models.IntegerField(default=10)),
                ('pulse_min', models.IntegerField(default=1)),
                ('weight_max', models.FloatField(default=10.0)),
                ('weight_min', models.FloatField(default=1.0)),
                ('bmi_max', models.FloatField(default=10.0)),
                ('bmi_min', models.FloatField(default=1.0)),
                ('body_fat_max', models.FloatField(default=10.0)),
                ('body_fat_min', models.FloatField(default=1.0)),
                ('created_at', models.CharField(default='2023-12-07 21:38:33:38:33', max_length=50)),
                ('updated_at', models.CharField(default='2023-12-07 21:38:33:38:33', max_length=50)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'User_Default',
            },
        ),
        migrations.CreateModel(
            name='User_Care',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.IntegerField(default=0)),
                ('reply_id', models.IntegerField(default=0)),
                ('message', models.CharField(default='', max_length=255, null=True)),
                ('created_at', models.DateTimeField(default='2023-12-07 21')),
                ('updated_at', models.DateTimeField(default='2023-12-07 21')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'User_Care',
            },
        ),
        migrations.CreateModel(
            name='User_Blood_Sugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sugar', models.FloatField(default=0)),
                ('timeperiod', models.IntegerField(default=0)),
                ('drug', models.IntegerField(default=0)),
                ('exercise', models.IntegerField(default=0)),
                ('recorded_at', models.DateTimeField(default='2023-12-07 21:38:33')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'User_Blood_Sugar',
            },
        ),
        migrations.CreateModel(
            name='User_Blood_Pressure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systolic', models.IntegerField(default=0)),
                ('diastolic', models.IntegerField(default=0)),
                ('pulse', models.IntegerField(default=0)),
                ('recorded_at', models.DateTimeField(default='2023-12-07 21:38:33')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'User_Blood_Pressure',
            },
        ),
        migrations.CreateModel(
            name='User_A1c',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a1c', models.FloatField(default=0)),
                ('recorded_at', models.DateTimeField(default='2023-12-07 21:38:33')),
                ('created_at', models.DateTimeField(default='2023-12-07 21:38:33')),
                ('updated_at', models.DateTimeField(default='2023-12-07 21:38:33')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'User_A1c',
            },
        ),
    ]
