# Generated by Django 4.2.5 on 2023-10-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Body', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDeafult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('suger_delta_max', models.FloatField()),
            ],
        ),
    ]
