# Generated by Django 4.2.5 on 2023-11-22 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Body', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloodsuger',
            old_name='execrise',
            new_name='exercise',
        ),
    ]
