# Generated by Django 4.2.5 on 2023-11-24 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Body', '0002_rename_execrise_bloodsuger_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodsuger',
            name='sugar',
            field=models.IntegerField(),
        ),
    ]
