# Generated by Django 4.2.7 on 2023-12-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Body', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_a1c',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='user_blood_pressure',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='user_blood_sugar',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='user_care',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='user_default',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='user_diary',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='user_drug',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='user_medical',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='user_setting',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='user_vip',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='user_weight',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='user_a1c',
            name='created_at',
            field=models.DateTimeField(default='2023-12-03 02:43:02'),
        ),
        migrations.AlterField(
            model_name='user_a1c',
            name='recorded_at',
            field=models.DateTimeField(default='2023-12-03 02:43:02'),
        ),
        migrations.AlterField(
            model_name='user_a1c',
            name='updated_at',
            field=models.DateTimeField(default='2023-12-03 02:43:02'),
        ),
        migrations.AlterField(
            model_name='user_blood_pressure',
            name='recorded_at',
            field=models.DateTimeField(default='2023-12-03 02:43:02'),
        ),
        migrations.AlterField(
            model_name='user_blood_sugar',
            name='recorded_at',
            field=models.DateTimeField(default='2023-12-03 02:43:02'),
        ),
        migrations.AlterField(
            model_name='user_care',
            name='created_at',
            field=models.DateTimeField(default='2023-12-03 02:43:02'),
        ),
        migrations.AlterField(
            model_name='user_care',
            name='updated_at',
            field=models.DateTimeField(default='2023-12-03 02:43:02'),
        ),
        migrations.AlterField(
            model_name='user_default',
            name='created_at',
            field=models.CharField(default='2023-12-03 02:43:02:43:02', max_length=50),
        ),
        migrations.AlterField(
            model_name='user_default',
            name='updated_at',
            field=models.CharField(default='2023-12-03 02:43:02:43:02', max_length=50),
        ),
        migrations.AlterField(
            model_name='user_diary',
            name='recorded_at',
            field=models.DateTimeField(default='2023-12-03 02:43:02'),
        ),
        migrations.AlterField(
            model_name='user_drug',
            name='created_at',
            field=models.DateTimeField(default='2023-12-03 02:43:02'),
        ),
        migrations.AlterField(
            model_name='user_drug',
            name='recorded_at',
            field=models.DateTimeField(default='2023-12-03 02:43:02'),
        ),
        migrations.AlterField(
            model_name='user_drug',
            name='updated_at',
            field=models.DateTimeField(default='2023-12-03 02:43:02'),
        ),
        migrations.AlterField(
            model_name='user_medical',
            name='created_at',
            field=models.DateTimeField(default='2023-12-03 02:43:02'),
        ),
        migrations.AlterField(
            model_name='user_medical',
            name='updated_at',
            field=models.DateTimeField(default='2023-12-03 02:43:02'),
        ),
        migrations.AlterField(
            model_name='user_setting',
            name='created_at',
            field=models.CharField(default='2023-12-03 02:43:02:43:02', max_length=50),
        ),
        migrations.AlterField(
            model_name='user_setting',
            name='updated_at',
            field=models.CharField(default='2023-12-03 02:43:02:43:02', max_length=50),
        ),
        migrations.AlterField(
            model_name='user_vip',
            name='created_at',
            field=models.DateTimeField(default='2023-12-03 02:43:02'),
        ),
        migrations.AlterField(
            model_name='user_vip',
            name='ended_at',
            field=models.DateTimeField(default='2023-12-03 02:43:02'),
        ),
        migrations.AlterField(
            model_name='user_vip',
            name='started_at',
            field=models.DateTimeField(default='2023-12-03 02:43:02'),
        ),
        migrations.AlterField(
            model_name='user_vip',
            name='updated_at',
            field=models.DateTimeField(default='2023-12-03 02:43:02'),
        ),
        migrations.AlterField(
            model_name='user_weight',
            name='recorded_at',
            field=models.DateTimeField(default='2023-12-03 02:43:02'),
        ),
    ]
