# Generated by Django 4.2.5 on 2023-11-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Body', '0003_alter_userprofile_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(default='2020-01-01 00:00:00'),
        ),
    ]
