# Generated by Django 4.2.6 on 2023-10-19 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Body', '0003_rename_suger_delta_max_userdeafult_bmi_max_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sugar_delta_max', models.FloatField(default=10.0)),
                ('sugar_delta_min', models.FloatField(default=1.0)),
                ('sugar_morning_max', models.FloatField(default=10.0)),
                ('sugar_morning_min', models.FloatField(default=1.0)),
                ('sugar_evening_max', models.FloatField(default=10.0)),
                ('sugar_evening_min', models.FloatField(default=1.0)),
                ('sugar_before_max', models.FloatField(default=10.0)),
                ('sugar_before_min', models.FloatField(default=1.0)),
                ('sugar_after_max', models.FloatField(default=10.0)),
                ('sugar_after_min', models.FloatField(default=1.0)),
                ('systolic_max', models.IntegerField(default=10)),
                ('systolic_min', models.IntegerField(default=1)),
                ('diastolic_max', models.IntegerField(default=10)),
                ('diastolic_min', models.IntegerField(default=1)),
                ('pulse_max', models.IntegerField(default=10)),
                ('pulse_min', models.IntegerField(default=1)),
                ('weight_max', models.FloatField(default=10.0)),
                ('weight_min', models.FloatField(default=1.0)),
                ('bmi_max', models.FloatField(default=10.0)),
                ('bmi_min', models.FloatField(default=1.0)),
                ('body_fat_max', models.FloatField(default=10.0)),
                ('body_fat_min', models.FloatField(default=1.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '使用者預設值',
                'verbose_name_plural': '使用者預設值',
                'db_table': 'user_default',
            },
        ),
        migrations.AlterModelOptions(
            name='usersetting',
            options={'verbose_name': '使用者設定', 'verbose_name_plural': '使用者設定'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='setting',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='Body.usersetting'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='after_meal',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='after_recording',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='no_recording_for_a_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='over_max_or_under_min',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='unit_of_height',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='unit_of_sugar',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='unit_of_weight',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterModelTable(
            name='usersetting',
            table='user_setting',
        ),
        migrations.DeleteModel(
            name='UserDeafult',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='Body.userdefault'),
            preserve_default=False,
        ),
    ]
