# Generated by Django 4.2.6 on 2023-11-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Body', '0003_alter_bloodsuger_sugar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='invite_code',
            field=models.CharField(default='1', max_length=10),
        ),
    ]
