# Generated by Django 4.2.5 on 2023-11-15 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Body', '0005_alter_userdefault_options_unread_records_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
    ]
