# Generated by Django 4.2.6 on 2023-10-19 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Body', '0006_alter_userdefault_table_alter_userprofile_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='default',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='setting',
        ),
    ]
