# Generated by Django 4.2.5 on 2023-11-15 20:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Body', '0006_alter_userprofile_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unread_records',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='unread_records',
            name='ended_at',
        ),
        migrations.RemoveField(
            model_name='unread_records',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='vip',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vip',
            name='ended_at',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vip',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
