# Generated by Django 4.2.5 on 2023-11-15 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Body', '0008_alter_vip_created_at_alter_vip_ended_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloodsuger',
            options={},
        ),
        migrations.AlterModelOptions(
            name='diet',
            options={},
        ),
        migrations.AlterModelOptions(
            name='weight',
            options={},
        ),
    ]
