# Generated by Django 4.2.5 on 2023-10-23 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Body', '0008_bloodpressure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('body_fat', models.FloatField()),
                ('bmi', models.FloatField()),
                ('recorded_at', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '體重',
                'verbose_name_plural': '體重',
                'db_table': 'Body_Weight',
            },
        ),
        migrations.CreateModel(
            name='Medical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diabets_type', models.IntegerField()),
                ('oad', models.IntegerField()),
                ('insulin', models.IntegerField()),
                ('antu_hypertensive', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '病史',
                'verbose_name_plural': '病史',
                'db_table': 'Body_Medical',
            },
        ),
        migrations.CreateModel(
            name='Drug_Used',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('recorded_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '藥物使用紀錄',
                'verbose_name_plural': '藥物使用紀錄',
                'db_table': 'Body_Drug_Used',
            },
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('meal', models.IntegerField()),
                ('tag', models.CharField(max_length=100)),
                ('image', models.IntegerField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('recorded_at', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '飲食日記',
                'verbose_name_plural': '飲食日記',
                'db_table': 'Body_Diet',
            },
        ),
        migrations.CreateModel(
            name='Care',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.IntegerField()),
                ('reply_id', models.IntegerField()),
                ('message', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '照護者',
                'verbose_name_plural': '照護者',
                'db_table': 'Body_Care',
            },
        ),
        migrations.CreateModel(
            name='BloodSuger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sugar', models.FloatField()),
                ('timeperiod', models.IntegerField()),
                ('recorded_at', models.CharField(max_length=50)),
                ('drug', models.IntegerField()),
                ('exercise', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '血糖',
                'verbose_name_plural': '血糖',
                'db_table': 'Body_Blood_Suger',
            },
        ),
        migrations.CreateModel(
            name='A1c',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aic', models.CharField(max_length=50)),
                ('recorded_at', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'A1c',
                'verbose_name_plural': 'A1c',
                'db_table': 'Body_A1c',
            },
        ),
    ]
