# Generated by Django 4.2.5 on 2023-11-15 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Body', '0009_alter_bloodsuger_options_alter_diet_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodpressure',
            name='diastolic',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='bloodpressure',
            name='pulse',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='bloodpressure',
            name='systolic',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='medical',
            name='antu_hypertensive',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='medical',
            name='created_at',
            field=models.DateTimeField(default='2020-01-01 00:00:00'),
        ),
        migrations.AlterField(
            model_name='medical',
            name='diabets_type',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='medical',
            name='insulin',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='medical',
            name='oad',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='medical',
            name='updated_at',
            field=models.DateTimeField(default='2020-01-01 00:00:00'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(default='abc', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.CharField(default='2020-01-01 00:00:00', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.CharField(default='2020-01-01 00:00:00', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='height',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(default='2020-01-01 00:00:00', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(default='2020-01-01 00:00:00'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weight',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='vip',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
