# Generated by Django 4.2.5 on 2023-10-24 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Body', '0010_vip_unread_records'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloodsuger',
            old_name='exercise',
            new_name='execrise',
        ),
    ]
