# Generated by Django 4.2.5 on 2023-11-16 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Body', '0010_alter_bloodpressure_diastolic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='invite_code',
            field=models.IntegerField(default=12345),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vip',
            name='remark',
            field=models.FloatField(default=1.0, max_length=100),
        ),
    ]
