# Generated by Django 4.2.5 on 2023-11-16 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Body', '0011_userprofile_invite_code_alter_vip_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical',
            name='created_at',
            field=models.DateTimeField(default='2020-01-01 01:01:00'),
        ),
        migrations.AlterField(
            model_name='medical',
            name='updated_at',
            field=models.DateTimeField(default='2020-01-01 01:01:00'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.CharField(default='2020-01-01 01:01:00', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(default='2020-01-01 01:01:00'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.CharField(default='2020-01-01 01:01:00', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(default='2020-01-01 01:01:00', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(default='2020-01-01 01:01:00'),
        ),
        migrations.AlterField(
            model_name='vip',
            name='created_at',
            field=models.DateTimeField(default='2020-01-01 01:01:00'),
        ),
        migrations.AlterField(
            model_name='vip',
            name='ended_at',
            field=models.DateTimeField(default='2020-01-01 01:01:00'),
        ),
        migrations.AlterField(
            model_name='vip',
            name='started_at',
            field=models.CharField(default='2020-01-01 01:01:00', max_length=50),
        ),
        migrations.AlterField(
            model_name='vip',
            name='updated_at',
            field=models.DateTimeField(default='2020-01-01 01:01:00'),
        ),
    ]
