# Generated by Django 4.2.5 on 2023-10-24 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Body', '0011_rename_exercise_bloodsuger_execrise'),
    ]

    operations = [
        migrations.RenameField(
            model_name='a1c',
            old_name='aic',
            new_name='a1c',
        ),
    ]
