# Generated by Django 4.2.5 on 2023-11-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Body', '0013_alter_a1c_created_at_alter_a1c_recorded_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='invite_code',
            field=models.IntegerField(default=1),
        ),
    ]
