# Generated by Django 4.2.6 on 2023-11-17 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Body', '0014_alter_medical_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medical',
            old_name='diabets_type',
            new_name='diabetes_type',
        ),
    ]
