# Generated by Django 4.2.5 on 2023-11-19 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Body', '0014_alter_userprofile_invite_code'),
        ('Body', '0016_rename_anti_hypertensive_medical_anti_hypertensives'),
    ]

    operations = [
    ]
