# Generated by Django 4.2.5 on 2023-10-14 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frined',
            name='code',
            field=models.CharField(default=datetime.datetime(2023, 10, 14, 12, 20, 3, 246932, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
    ]
