# Generated by Django 4.2.5 on 2023-10-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0002_frined_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frined',
            name='read',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='frined',
            name='relation_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='frined',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='frined',
            name='type',
            field=models.IntegerField(null=True),
        ),
    ]
