# Generated by Django 4.2.5 on 2023-10-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0004_alter_frined_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frined',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
