# Generated by Django 4.2.5 on 2023-10-14 13:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friend', '0005_alter_frined_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='frined',
            new_name='friend',
        ),
    ]
