# Generated by Django 4.2.5 on 2023-10-20 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friend', '0006_rename_frined_friend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='code',
        ),
        migrations.AlterField(
            model_name='friend',
            name='friend',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='friend', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='friend',
            name='type',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
