# Generated by Django 4.2.6 on 2023-12-07 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('relation_id', models.IntegerField(default=0, null=True)),
                ('name', models.CharField(default='', max_length=255, null=True)),
                ('relation_type', models.IntegerField(default=0, null=True)),
                ('status', models.IntegerField(default=0, null=True)),
                ('read', models.IntegerField(default=0, null=True)),
                ('created_at', models.DateTimeField(default='2023-12-07 21:38:43')),
                ('updated_at', models.DateTimeField(default='2023-12-07 21:38:43')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
