# Generated by Django 4.2.7 on 2023-11-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_id', models.IntegerField(default=0, null=True)),
                ('name', models.CharField(default='', max_length=255, null=True)),
                ('relation_type', models.IntegerField(default=0, null=True)),
                ('status', models.IntegerField(default=0, null=True)),
                ('read', models.IntegerField(default=0, null=True)),
                ('created_at', models.DateTimeField(default='2023-11-26 23:34:32')),
                ('updated_at', models.DateTimeField(default='2023-11-26 23:34:32')),
            ],
        ),
    ]
