# Generated by Django 4.2.6 on 2023-12-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Friend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='created_at',
            field=models.DateTimeField(default='2023-12-07 21:38:53'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='updated_at',
            field=models.DateTimeField(default='2023-12-07 21:38:53'),
        ),
    ]
