# Generated by Django 4.2.6 on 2023-11-25 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Friend', '0002_remove_friend_friend_alter_friend_status_friend_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.DeleteModel(
            name='Invite',
        ),
    ]
