# Generated by Django 4.2.6 on 2023-11-26 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Friend', '0003_alter_friend_status_delete_invite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='relation_id',
            field=models.IntegerField(default=0),
        ),
    ]
