# Generated by Django 4.2.7 on 2023-11-26 15:34

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.CharField(default='', max_length=50, unique=True)),
                ('verify_code', models.CharField(default='', max_length=50)),
                ('is_verify', models.BooleanField(default=False)),
                ('account', models.CharField(default='', max_length=50)),
                ('verification_code', models.CharField(default='', max_length=50)),
                ('name', models.CharField(default='USER', max_length=50)),
                ('birthday', models.CharField(default='', max_length=50)),
                ('height', models.FloatField(default=1.0)),
                ('weight', models.FloatField(default=1.0)),
                ('phone', models.CharField(default='', max_length=50)),
                ('gender', models.BooleanField(default=True)),
                ('fcm_id', models.CharField(max_length=100)),
                ('address', models.CharField(default='', max_length=100)),
                ('must_change_password', models.IntegerField(default=0)),
                ('status', models.CharField(default='VIP', max_length=20)),
                ('invite_code', models.CharField(default='', max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'User_Info',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='News_Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.IntegerField(default=0)),
                ('group', models.IntegerField(default=0)),
                ('title', models.CharField(default='0', max_length=50)),
                ('message', models.CharField(default='0', max_length=50)),
                ('data_type', models.IntegerField()),
                ('relation_type', models.IntegerField()),
                ('pushed_at', models.CharField(default='2023-11-26 23:34:32', max_length=50)),
                ('created_at', models.CharField(default='2023-11-26 23:34:32', max_length=50)),
                ('updated_at', models.CharField(default='2023-11-26 23:34:32', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'News_Share',
            },
        ),
    ]
