# Generated by Django 4.2.7 on 2023-12-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news_share',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='user_info',
            name='badge',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_info',
            name='created_at',
            field=models.CharField(default='2023-12-03 02:43:02', max_length=50),
        ),
        migrations.AddField(
            model_name='user_info',
            name='login_times',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_info',
            name='updated_at',
            field=models.CharField(default='2023-12-03 02:43:02', max_length=50),
        ),
        migrations.AlterField(
            model_name='news_share',
            name='created_at',
            field=models.CharField(default='2023-12-03 02:43:02', max_length=50),
        ),
        migrations.AlterField(
            model_name='news_share',
            name='pushed_at',
            field=models.CharField(default='2023-12-03 02:43:02', max_length=50),
        ),
        migrations.AlterField(
            model_name='news_share',
            name='updated_at',
            field=models.CharField(default='2023-12-03 02:43:02', max_length=50),
        ),
    ]
