# Generated by Django 4.2.6 on 2023-10-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='verify',
            field=models.BooleanField(default=False),
        ),
    ]
