# Generated by Django 4.2.5 on 2023-10-16 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_account_options_alter_account_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'account', 'verbose_name_plural': 'account'},
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterModelTable(
            name='account',
            table='account',
        ),
    ]
