# Generated by Django 4.2.6 on 2023-10-19 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_share'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='share',
            options={'verbose_name': 'share', 'verbose_name_plural': 'share'},
        ),
        migrations.AlterModelTable(
            name='account',
            table='User_account',
        ),
        migrations.AlterModelTable(
            name='news',
            table='User_news',
        ),
        migrations.AlterModelTable(
            name='share',
            table='User_share',
        ),
    ]
