# Generated by Django 4.2.6 on 2023-10-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(max_length=50),
        ),
        migrations.AlterField(
            model_name='news',
            name='group',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='news',
            name='member_id',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='news',
            name='pushed_at',
            field=models.DateTimeField(max_length=50),
        ),
        migrations.AlterField(
            model_name='news',
            name='updated_at',
            field=models.DateTimeField(max_length=50),
        ),
    ]
