# Generated by Django 4.2.6 on 2023-10-19 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_alter_share_options_alter_account_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='account',
            table='User_Account',
        ),
        migrations.AlterModelTable(
            name='news',
            table='User_News',
        ),
        migrations.AlterModelTable(
            name='share',
            table='User_Share',
        ),
    ]
