# Generated by Django 4.2.5 on 2023-11-15 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_alter_account_table_alter_news_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={},
        ),
    ]
