# Generated by Django 4.2.7 on 2023-12-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_remove_user_info_name_alter_news_share_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_share',
            name='created_at',
            field=models.CharField(default='2023-12-03 03:07:06', max_length=50),
        ),
        migrations.AlterField(
            model_name='news_share',
            name='data_type',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='news_share',
            name='pushed_at',
            field=models.CharField(default='2023-12-03 03:07:06', max_length=50),
        ),
        migrations.AlterField(
            model_name='news_share',
            name='updated_at',
            field=models.CharField(default='2023-12-03 03:07:06', max_length=50),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='created_at',
            field=models.CharField(default='2023-12-03 03:07:06', max_length=50),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='updated_at',
            field=models.CharField(default='2023-12-03 03:07:06', max_length=50),
        ),
    ]
